services:
  backend:
    build: .
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend.env:/app/solar_backend/backend.env
    environment:
      - ENV_FILE=backend.env

  # influxdb:
  #   image: "influxdb:2.7-alpine"
  #   ports:
  #     - 8086:8086
  #   volumes:
  #     - influxdb:/var/lib/influxdb2:rw
  #   env_file:
  #     - influxdb.env

  db:
    image: timescale/timescaledb:latest-pg16
    restart: always
    environment:
      POSTGRES_USER: deyehard
      POSTGRES_PASSWORD: dev-testing-ok
      POSTGRES_DB: deyehard
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U deyehard"]
      interval: 2s

volumes:
  pgdata:
  # influxdb:
