version: '3'
services:
  backend:
    build: .
    ports:
      - 8000:80
    depends_on:
      db:
        condition: service_healthy
    volumes:
      - ./backend.env:/app/solar_backend/backend.env
    environment:
      - ENV_FILE=backend.env

  influxdb:
    image: "influxdb:2.7-alpine@sha256:327be0243a329b1da350a37c1468d756f4258330d50d10a2a993e5bb9a6e3d2e"
    ports:
    - 8086:8086
    volumes:
      - influxdb:/var/lib/influxdb2:rw
    env_file: 
      - influxdb.env

  db:
    image: postgres:16-alpine@sha256:d898b0b78a2627cb4ee63464a14efc9d296884f1b28c841b0ab7d7c42f1fffdf
    restart: always
    environment:
      POSTGRES_USER: deyehard
      POSTGRES_PASSWORD: dev-testing-ok
      POSTGRES_DB: deyehard
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready"]
      interval: 2s

volumes:
  pgdata:
  influxdb: